# Generated by Django 3.1.5 on 2021-09-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csm',
            fields=[
                ('csmid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('csmFirstName', models.CharField(max_length=30)),
                ('csmLastName', models.CharField(max_length=20)),
                ('csmShortName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('CustomerId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ProductCount', models.CharField(max_length=20)),
                ('CustomerName', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='division',
            fields=[
                ('divisionid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryDomain',
            fields=[
                ('ind_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ind_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('productid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('division', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='testapp.division')),
                ('industry', models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='testapp.industrydomain')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('projectid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_success_manager', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='testapp.csm')),
                ('customername', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('RegionId', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('RegionName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('ResourceId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ResourceEmail', models.CharField(max_length=50)),
                ('ResourceFirstName', models.CharField(max_length=30)),
                ('ResourceLastName', models.CharField(max_length=20)),
                ('ResourceShortName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stage',
            fields=[
                ('stageId', models.CharField(default=1, max_length=10, primary_key=True, serialize=False)),
                ('stageName', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='storeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeinfo_text', models.CharField(blank=True, max_length=5000, null=True)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.customer')),
                ('direct_product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.product')),
                ('project', models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='testapp.projects')),
                ('resource', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='testapp.resource')),
            ],
        ),
        migrations.CreateModel(
            name='SaleStage',
            fields=[
                ('sales_Name', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.product')),
                ('sales_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.stage')),
            ],
        ),
        migrations.CreateModel(
            name='questionAnswer',
            fields=[
                ('questionId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('question', models.CharField(default='Test', max_length=2000)),
                ('textinput', models.CharField(max_length=300)),
                ('answer', models.ForeignKey(default='True', on_delete=django.db.models.deletion.CASCADE, to='testapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='resource',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='testapp.resource'),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('outputId', models.CharField(default=500, max_length=100, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='testapp.customer')),
                ('recommended_products', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.product')),
                ('resource', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.resource')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.region'),
        ),
    ]
