# Generated by Django 3.1.5 on 2021-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='textinput',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
