# Generated by Django 3.1.5 on 2021-09-02 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210901_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Allocation_end_date',
            field=models.DateField(default=datetime.date(2021, 9, 2)),
        ),
        migrations.AddField(
            model_name='projects',
            name='Allocation_start_date',
            field=models.DateField(default=datetime.date(2021, 9, 2)),
        ),
    ]
